package com.ipn.sigep.preregistro.domain;
// Generated 16/03/2020 10:38:49 PM by Hibernate Tools 5.0.6.Final


import java.util.Date;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.FetchType;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.OneToOne;
import javax.persistence.PrimaryKeyJoinColumn;
import javax.persistence.Table;
import javax.persistence.Temporal;
import javax.persistence.TemporalType;
import javax.persistence.UniqueConstraint;
import lombok.AllArgsConstructor;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.hibernate.annotations.DynamicUpdate;
import org.hibernate.annotations.GenericGenerator;
import org.hibernate.annotations.Parameter;

/**
 * Alumnos generated by hbm2java.
 */
@AllArgsConstructor

/**
 * Instantiates a new alumnos.
 */
@NoArgsConstructor
@DynamicUpdate
@Entity
@Data
@Table(name = "alumnos", catalog = "sigep_db", uniqueConstraints = {
    @UniqueConstraint(columnNames = "boleta"), @UniqueConstraint(columnNames = "curp")})
public class Alumnos implements java.io.Serializable {
  /**
   * serialVersionUID generado automaticamente.
   */
  private static final long serialVersionUID = 6518644067224217113L;
  @Id
  @GenericGenerator(name = "generatorUser", strategy = "foreign",
      parameters = @Parameter(name = "property", value = "usuarios"))
  @GeneratedValue(generator = "generatorUser")
  @Column(name = "idUsuario", unique = true, nullable = false)
  private Integer idUsuario;
  @OneToOne(fetch = FetchType.LAZY)
  @PrimaryKeyJoinColumn
  private Usuarios usuarios;
  @Column(name = "idProgramaAcademico", nullable = false)
  private Integer idProgramaAcademico;
  @Column(name = "nombre", nullable = false, length = 45)
  private String nombre;
  @Column(name = "apellidoPaterno", nullable = false, length = 45)
  private String apellidoPaterno;
  @Column(name = "apellidoMaterno", length = 45)
  private String apellidoMaterno;
  @Column(name = "boleta", unique = true, nullable = false, length = 60)
  private String boleta;
  @Column(name = "curp", unique = true, nullable = false, length = 18)
  private String curp;
  @Column(name = "genero", nullable = false, length = 1)
  private String genero;
  @Column(name = "creditos", precision = 10, scale = 0)
  private Long creditos;
  @Column(name = "estatus", nullable = false)
  private Integer estatus;
  @Column(name = "fechaCreacion", nullable = false, length = 19)
  private Date fechaCreacion;
  @Temporal(TemporalType.TIMESTAMP)
  @Column(name = "fechaActualizacion", length = 19)
  private Date fechaActualizacion;
  @Column(name = "correoElectronico", length = 45)
  private String correoElectronico;
}


