package com.ipn.sigep.preregistro.domain;
// Generated 27/02/2020 12:10:05 AM by Hibernate Tools 5.0.6.Final


import com.ipn.sigep.preregistro.constant.Constants;
import io.swagger.annotations.ApiModelProperty;
import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.Id;
import javax.persistence.Table;
import lombok.Data;


/**
 * VProgramasacademicos generated by hbm2java.
 */
@Entity

/**
 * Instantiates a new v programasacademicos.
 */
@Data
@Table(name = "v_programasacademicos", catalog = "sigep_db")
public class VProgramasacademicos implements java.io.Serializable {


  /**
   * Serial version.
   */
  private static final long serialVersionUID = 8061955502325354661L;
  
  /** The id programa academico. */
  @Id
  @Column(name = "idProgramaAcademico", nullable = false)
  @ApiModelProperty(position = Constants.VALOR_INT_1, example = "1")
  private Integer idProgramaAcademico;
  
  /** The id unidad academica. */
  @Column(name = "idUnidadAcademica", nullable = false,  length = 5)
  private Integer idUnidadAcademica;
  
  /** The clave. */
  @Column(name = "clave", nullable = false, length = 5)
  @ApiModelProperty(position = Constants.VALOR_INT_2, example = "67")
  private String clave;
  
  /** The nivel. */
  @Column(name = "nivel", nullable = false, length = 100)
  @ApiModelProperty(position = Constants.VALOR_INT_3, example = "MAESTRIA")
  private String nivel;
  
  /** The programa academico. */
  @Column(name = "programaAcademico", length = 212)
  @ApiModelProperty(position = Constants.VALOR_INT_4,
      example = "MAESTRIA EN CIENCIAS EN ARQUITECTURA Y URBANISMO PLAN 2008")
  private String programaAcademico;



}


