package com.ipn.sigep.preregistro.constant;

import java.io.Serializable;
import lombok.Getter;
import org.springframework.beans.factory.annotation.Value;
import org.springframework.boot.context.properties.ConfigurationProperties;
import org.springframework.boot.context.properties.EnableConfigurationProperties;
import org.springframework.stereotype.Component;


/**
 * The Class ApiConstants.
 */
@Component
@EnableConfigurationProperties
@ConfigurationProperties

/**
 * Gets the mail.
 *
 * @return the mail
 */
@Getter
public class ApiConstants implements Serializable {
    
  /**
   * Serial version automatic generated by IDE.
   */
  private static final long serialVersionUID = -7332787062451424993L;

  /** The base package. */
  @Value("${constants.swagger.config.basePackage}")
  private String basePackage;
  
  /** The regex. */
  @Value("${constants.swagger.config.regex}")
  private String regex;
  
  /** The tittle. */
  @Value("${constants.swagger.info.tittle}")
  private String tittle;
  
  /** The description. */
  @Value("${constants.swagger.info.description}")
  private String description;
  
  /** The version. */
  @Value("${constants.swagger.info.version}")
  private String version;
  
  /** The name. */
  @Value("${constants.swagger.contact.name}")
  private String name;
  
  /** The url. */
  @Value("${constants.swagger.contact.url}")
  private String url;
  
  /** The mail. */
  @Value("${constants.swagger.contact.mail}")
  private String mail;

  /** The Constant OK. */
  public static final String OK = "${constants.apiMsg.ok}";

  /** The Constant BAD_REQUEST. */
  public static final String BAD_REQUEST = "${constants.apiMsg.badRequest}";

  /** The Constant UNAUTHORIZED. */
  public static final String UNAUTHORIZED = "${constants.apiMsg.unauthorized}";

  /** The Constant ACCESS_NOT_CONFIGURED. */
  public static final String ACCESS_NOT_CONFIGURED = "${constants.apiMsg.accesNotConfigured}";

  /** The Constant NOT_FOUND. */
  public static final String NOT_FOUND = "${constants.apiMsg.notFound}";

  /** The Constant BUSINESS_VALIDATION_FAILED. */
  public static final String BUSINESS_VALIDATION_FAILED =
      "${constants.apiMsg.businessValidationFailed}";

  /** The Constant INTERNAL_ERROR. */
  public static final String INTERNAL_ERROR = "${constants.apiMsg.internalError}";
  
  /** The Constant PREREGISTRO_GRAL_PATH. */
  public static final String PREREGISTRO_GRAL_PATH = "";
  
  /** The Constant PREREGISTRO_CONSULTA_GRAL_PATH. */
  public static final String PREREGISTRO_CONSULTA_GRAL_PATH = "";
  
  /** The Constant PREREGISTRO_CONSULTA_GRAL_DESC. */
  public static final String PREREGISTRO_CONSULTA_GRAL_DESC = "";
  
  /** The Constant PREREGISTRO_CONSULTA_GRAL_RESPMSG. */
  public static final String PREREGISTRO_CONSULTA_GRAL_RESPMSG = "";
  
  
  
}
