server:
  port: 9100
spring:
  application:
    name: ms-sigep-autorizador
  security:
    user:
      name: "admin"
      password: "admin123"
eureka:
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${spring.application.instance_id:${random.value}}
    leaseRenewalIntervalInSeconds: 1
    leaseExpirationDurationInSeconds: 2
management:
  endpoints:
    web:
      exposure:
        include: "*"
  
